print("This is a BAND NAME GENERATOR")
print("-based on city you live in and the pet name you own")
city=input("Enter the city you live in-->\n").upper()
pet=input("Enter your pet's name -->\n").upper()
print("Your Band name is "+city+" "+pet)